    CREATE DATABASE ConnectPlus_Moura;
	GO

	USE ConnectPlus_Moura;
	GO

	CREATE TABLE Contato(
	IdContato UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
	Nome NVARCHAR(100) NOT NULL,
	Numero NVARCHAR(90) NOT NULL UNIQUE
	);
	GO

	CREATE TABLE TipoContato(
	IdTipoContato UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
	Nome NVARCHAR(100) NOT NULL,
	SMS  NVARCHAR(10)  NULL,
	Email NVARCHAR(100)  NULL,
	IdContato INT,
	FOREIGN KEY(IdTipoContato) REFERENCES Contato(IdContato)
	);

